version: 2.1

executors:
  ruby_docker:
    docker:
      - image: circleci/ruby:3.0.3
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

jobs:
  build:
    executor: ruby_docker
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

